# Change these first
owner: Linisdjxm # Your GitHub organization or username, where this repository lives
repo: uptest # The name of this repository

sites:
  - name: QW
    url: https://zhqw.qiuwen.wiki

status-website:
  baseUrl: /uptest # where "repo" is your repository name
  name: The Status Website
