# Change these first
owner: Linisdjxm # Your GitHub organization or username, where this repository lives
repo: uptest # The name of this repository

sites:
  - name: GW
    url: https://www.gfwiki.org
  - name: MW
    url: https://zh.moegirl.org.cn
  - name: IMWB
    url: https://www.ismoegirl.online

status-website:
  baseUrl: /uptest # where "repo" is your repository name
  name: The Status Website
